#---Model---
# Tracker model to evaluate (Options: 'RadarMOTR', 'SORT'. Default is 'RadarMOTR')
tracker: 'KF'

# Name of the directory where the track files are stored
tracker_dirname: 'kf'

#---Tracker config---
# Maximum number of frames to keep alive a track without associated detections.
max_age: 5

# Minimum number of associated detections before track is initialized.
min_hits: 1

# Max distance between detection and prediction for a track
dist_threshold: 6

# Resolution to convert from image y coordinate to range (the range interval is inverted => 256 -> 0m, 0 -> 50m)
range_resolution: 0.1953125

# Resolution to convert from image x coordinate to velocity (the max velocity / 2 is subtracted to center the value)
velocity_resolution: 0.41968030701528203

# Time delta between frames
fps: 10

augment_data: false
