#---Miscellaneous---
device: 'cuda'
seed: 42

# Controls whether to allow TF32 on matmul. PyTorch default is false.
# https://pytorch.org/docs/stable/notes/cuda.html#tensorfloat-32-tf32-on-ampere-devices
allow_tf32_matmul: false

save_model_interval: 5

# Print statistics like time and loss every n training iterations
stats_print_freq: 10
# Whether to print gpu utilization and memory usage every n training iterations
print_gpu_info: true

# Resume from checkpoint
resume: ''
pretrained: null
backbone_weights: null

eval: false

# This will evaluate the validation dataset every n epochs starting with first
# To disable <= 0
validation_freq: 5
# Print statistics like time and loss every n validation iterations
val_stats_print_freq: 1
