# MOT settings
pretrained: 'data/models/motrv2_base_v2.pth'

##--Backbone--
# Name of the convolutional backbone to use. ('circular_resnet18', 'resnet18', 'resnet50', 'resnet101')
backbone: 'resnet50'
# Resnet weights to use ('ResNet50_Weights.IMAGENET1K_V1', 'ResNet50_Weights.DEFAULT'). null if resnet should be trained from ground up.
backbone_weights: 'ResNet50_Weights.IMAGENET1K_V1'
